### ISSUE TITLE
Not working on Kali Linux

### ISSUE THREAD

**Issue by JackTheGilis** [3ndG4me/torphantom#5]
torphantom start -i <interface(s)>
Not working on Kali Linux.

**Comment by 3ndG4me** [comment]
What errors are you getting? This appears to be working. If you could provide more information that would be helpful in diagnosing the issue.

Are you correctly specifying the interface(s)? Usually on Linux it'd be:
torphantom start -i eth0

OR

torphantom start -i wlan0

Depending on if you're using your default ethernet or wireless card. Those values differ based on distros and how your network adapters register in the system, but generally on Kali that'd be the default.

**Comment by 3ndG4me** [comment]
Please reopen/open a new issue and add new details if you are still experiencing this issue. Closing for now due to inactivity.
