### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/etc/tor/torrc'

### ISSUE THREAD

**Issue by W3ND1G000** [3ndG4me/torphantom#9]
I get the following error when attempting to run 'sudo torphantom start' on Parrot linux:

12:17:48] Changing MAC Addresses...
[12:17:48] Changing: wlan0
Current MAC:   0c:96:e6:c5:a1:2b (unknown)
Permanent MAC: 0c:96:e6:c5:a1:2b (unknown)
New MAC:       3e:0b:ee:5d:ef:bc (unknown)
[12:17:48] MAC Addresses changed
[12:17:48] Restarting Network Manager... [done]
Traceback (most recent call last):
  File "/usr/bin/torphantom", line 200, in <module>
    start_torphantom()
  File "/usr/bin/torphantom", line 120, in start_torphantom
    if TorrcCfgString in open(Torrc).read():
IOError: [Errno 2] No such file or directory: '/etc/tor/torrc'

**Comment by 3ndG4me** [comment]
Please insure TOR is already installed. It should create a torrc file in /etc/tor by default. If not you can find the sample default file here and manually create the directory in /etc/tor renaming the file to `torrc`

https://github.com/torproject/tor/blob/master/src/config/torrc.sample.in
